<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Assignment_1_b_svd_pritpal_sir_Shikhar_Aditya_2021MSBDA037.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving AirQualityUCI.csv to AirQualityUCI.csv


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/AirQualityUCI.csv',sep=';')

In [4]:
df.head()

Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  \
0  10/03/2004  18.00.00    2,6       1360.0     150.0     11,9         1046.0   
1  10/03/2004  19.00.00      2       1292.0     112.0      9,4          955.0   
2  10/03/2004  20.00.00    2,2       1402.0      88.0      9,0          939.0   
3  10/03/2004  21.00.00    2,2       1376.0      80.0      9,2          948.0   
4  10/03/2004  22.00.00    1,6       1272.0      51.0      6,5          836.0   

   NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH  \
0    166.0        1056.0    113.0        1692.0       1268.0  13,6  48,9   
1    103.0        1174.0     92.0        1559.0        972.0  13,3  47,7   
2    131.0        1140.0    114.0        1555.0       1074.0  11,9  54,0   
3    172.0        1092.0    122.0        1584.0       1203.0  11,0  60,0   
4    131.0        1205.0    116.0        1490.0       1110.0  11,2  59,6   

       AH  Unnamed: 15  Unnamed: 16  
0  0,7578          NaN          NaN  
1  0,7255          NaN          NaN  
2  0,7502          NaN          NaN  
3  0,7867          NaN          NaN  
4  0,7888          NaN          NaN

In [5]:
df1 = df[['PT08.S1(CO)','NMHC(GT)']]

In [6]:
first20 = df1.head(20)

In [7]:
first20

PT08.S1(CO)  NMHC(GT)
0        1360.0     150.0
1        1292.0     112.0
2        1402.0      88.0
3        1376.0      80.0
4        1272.0      51.0
5        1197.0      38.0
6        1185.0      31.0
7        1136.0      31.0
8        1094.0      24.0
9        1010.0      19.0
10       1011.0      14.0
11       1066.0       8.0
12       1052.0      16.0
13       1144.0      29.0
14       1333.0      64.0
15       1351.0      87.0
16       1233.0      77.0
17       1179.0      43.0
18       1236.0      61.0
19       1286.0      63.0

In [8]:
import numpy as np

In [9]:
matrix = first20.to_numpy()

In [10]:
matrix.shape

(20, 2)

In [11]:
matrix_t = matrix.transpose()

In [12]:
matrix_t

array([[1360., 1292., 1402., 1376., 1272., 1197., 1185., 1136., 1094.,
        1010., 1011., 1066., 1052., 1144., 1333., 1351., 1233., 1179.,
        1236., 1286.],
       [ 150.,  112.,   88.,   80.,   51.,   38.,   31.,   31.,   24.,
          19.,   14.,    8.,   16.,   29.,   64.,   87.,   77.,   43.,
          61.,   63.]])

In [13]:
matrix_t.shape

(2, 20)

In [14]:
square_matrix = np.matmul(matrix_t,matrix)

In [15]:
square_matrix

array([[29608123.,  1387506.],
       [ 1387506.,    84582.]])

In [16]:
square_matrix.shape

(2, 2)

In [17]:
from numpy.linalg import eig
eig(square_matrix)

(array([2.96731877e+07, 1.95173288e+04]), array([[ 0.99890232, -0.04684178],
        [ 0.04684178,  0.99890232]]))

In [18]:
e,v=eig(square_matrix)

In [19]:
e

array([2.96731877e+07, 1.95173288e+04])

In [20]:
v

array([[ 0.99890232, -0.04684178],
       [ 0.04684178,  0.99890232]])

In [21]:
sigma = [[2.96731877e+07,0],
         [0, 1.95173288e+04]]

In [22]:
def normalize_2d(matrix):
    norm = np.linalg.norm(matrix)
    matrix = matrix/norm  # normalized matrix
    return matrix

In [24]:
norm_v = normalize_2d(v)

In [26]:
sigma = np.sqrt(sigma)

In [27]:
sigma

array([[5447.31013437,    0.        ],
       [   0.        ,  139.70443372]])

In [30]:
matrix_t.shape

(2, 20)

In [29]:
v.shape

(2, 2)

In [32]:
cv = np.matmul(v,matrix_t)

In [33]:
cv

array([[1351.48089002, 1285.33551981, 1396.33897789, 1370.74225178,
        1268.21482198, 1193.90609102, 1182.24715563, 1133.30094188,
        1091.67493685, 1008.00135075, 1009.23446197, 1064.45514033,
        1050.09577359, 1141.38584401, 1328.53892044, 1345.44180128,
        1228.03974516, 1175.69164034, 1231.78592061, 1281.63735312],
       [ 213.54016932,  172.39664006,  153.57558017,  144.36647531,
         110.52676285,   94.02789915,   86.47348154,   84.17823431,
          75.21856329,   66.28934214,   61.34167232,   57.9245563 ,
          65.25998995,   82.55516391,  126.36984162,  150.18774706,
         134.67139377,   98.17925872,  118.82948197,  123.16937563]])

In [34]:
cv_norm = normalize_2d(cv)

In [35]:
cv_norm

array([[0.24801904, 0.23588028, 0.25625124, 0.25155382, 0.23273835,
        0.21910147, 0.21696186, 0.20797942, 0.20034036, 0.18498488,
        0.18521118, 0.19534508, 0.1927099 , 0.20946314, 0.24380881,
        0.24691077, 0.22536556, 0.21575882, 0.22605304, 0.2352016 ],
       [0.03918814, 0.03163763, 0.02818365, 0.02649363, 0.02028348,
        0.01725567, 0.01586931, 0.01544809, 0.01380385, 0.01216519,
        0.01125721, 0.01063011, 0.01197628, 0.01515023, 0.02319095,
        0.02756193, 0.02471442, 0.01801751, 0.02180717, 0.02260361]])

In [38]:
sigma.shape , cv_norm.shape

((2, 2), (2, 20))

In [40]:
np.matmul(sigma,cv_norm)

array([[1351.03664632, 1284.91301869, 1395.87998895, 1370.2916767 ,
        1267.79794858, 1193.51364356, 1181.85854056, 1132.92841586,
        1091.31609366, 1007.67001181, 1008.9027177 , 1064.10524453,
        1049.75059784, 1141.01066041, 1328.10221798, 1344.99954269,
        1227.63607766, 1175.30518012, 1231.38102171, 1281.21606761],
       [   5.47475754,    4.41991691,    3.93738128,    3.70127762,
           2.83369274,    2.41069374,    2.21701306,    2.15816736,
           1.9284587 ,    1.69953071,    1.57268201,    1.48507376,
           1.67314011,    2.11655497,    3.23987869,    3.85052378,
           3.45271445,    2.51712658,    3.04655843,    3.15782492]])