<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Assignment_1_Eigenv%26v_pritpal_sir_Shikhar_Aditya_2021MSBDA037.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving AirQualityUCI.csv to AirQualityUCI.csv


In [2]:
import pandas as pd

In [28]:
df = pd.read_csv('/content/AirQualityUCI.csv',sep=';')

In [29]:
df.head()

Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  \
0  10/03/2004  18.00.00    2,6       1360.0     150.0     11,9         1046.0   
1  10/03/2004  19.00.00      2       1292.0     112.0      9,4          955.0   
2  10/03/2004  20.00.00    2,2       1402.0      88.0      9,0          939.0   
3  10/03/2004  21.00.00    2,2       1376.0      80.0      9,2          948.0   
4  10/03/2004  22.00.00    1,6       1272.0      51.0      6,5          836.0   

   NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH  \
0    166.0        1056.0    113.0        1692.0       1268.0  13,6  48,9   
1    103.0        1174.0     92.0        1559.0        972.0  13,3  47,7   
2    131.0        1140.0    114.0        1555.0       1074.0  11,9  54,0   
3    172.0        1092.0    122.0        1584.0       1203.0  11,0  60,0   
4    131.0        1205.0    116.0        1490.0       1110.0  11,2  59,6   

       AH  Unnamed: 15  Unnamed: 16  
0  0,7578          NaN          NaN  
1  0,7255          NaN          NaN  
2  0,7502          NaN          NaN  
3  0,7867          NaN          NaN  
4  0,7888          NaN          NaN

In [39]:
df1 = df[['PT08.S1(CO)','NMHC(GT)']]

In [42]:
first20 = df1.head(20)

In [43]:
first20

PT08.S1(CO)  NMHC(GT)
0        1360.0     150.0
1        1292.0     112.0
2        1402.0      88.0
3        1376.0      80.0
4        1272.0      51.0
5        1197.0      38.0
6        1185.0      31.0
7        1136.0      31.0
8        1094.0      24.0
9        1010.0      19.0
10       1011.0      14.0
11       1066.0       8.0
12       1052.0      16.0
13       1144.0      29.0
14       1333.0      64.0
15       1351.0      87.0
16       1233.0      77.0
17       1179.0      43.0
18       1236.0      61.0
19       1286.0      63.0

In [44]:
import numpy as np

In [47]:
matrix = first20.to_numpy()

In [50]:
matrix.shape

(20, 2)

In [51]:
matrix_t = matrix.transpose()

In [52]:
matrix_t

array([[1360., 1292., 1402., 1376., 1272., 1197., 1185., 1136., 1094.,
        1010., 1011., 1066., 1052., 1144., 1333., 1351., 1233., 1179.,
        1236., 1286.],
       [ 150.,  112.,   88.,   80.,   51.,   38.,   31.,   31.,   24.,
          19.,   14.,    8.,   16.,   29.,   64.,   87.,   77.,   43.,
          61.,   63.]])

In [53]:
matrix_t.shape

(2, 20)

In [54]:
square_matrix = np.matmul(matrix_t,matrix)

In [55]:
square_matrix

array([[29608123.,  1387506.],
       [ 1387506.,    84582.]])

In [56]:
square_matrix.shape

(2, 2)

In [59]:
from numpy.linalg import eig
eig(square_matrix)

(array([2.96731877e+07, 1.95173288e+04]), array([[ 0.99890232, -0.04684178],
        [ 0.04684178,  0.99890232]]))