<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
data = np.array([[-1.2,0.3,1.5,2.3],[-2.5,2,1.0,1.4],[2.2,2.7,-2,-2.6],[-2.5,2.5,1,2.0]])

In [3]:
binarised = preprocessing.Binarizer(threshold=1.6).transform(data)

In [4]:
binarised

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 1.]])

In [6]:
print(binarised.mean(axis=0))
print(binarised.std(axis=0))

[0.25 0.75 0.   0.5 ]
[0.4330127 0.4330127 0.        0.5      ]


In [8]:
data_scaled = preprocessing.scale(data)

In [9]:
data_scaled

array([[-0.10404537, -1.66774084,  0.81150267,  0.77202821],
       [-0.7803403 ,  0.13236038,  0.45083482,  0.316405  ],
       [ 1.66472598,  0.87357853, -1.71317231, -1.70858701],
       [-0.7803403 ,  0.66180192,  0.45083482,  0.6201538 ]])

In [10]:
data_scaled.mean(axis=0)

array([ 2.77555756e-17,  8.32667268e-17, -2.77555756e-17,  0.00000000e+00])

In [11]:
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))

In [14]:
minmax_scaled = minmax_scaler.fit_transform(data)

In [15]:
minmax_scaled

array([[0.27659574, 0.        , 1.        , 1.        ],
       [0.        , 0.70833333, 0.85714286, 0.81632653],
       [1.        , 1.        , 0.        , 0.        ],
       [0.        , 0.91666667, 0.85714286, 0.93877551]])

In [16]:
preprocessing.normalize(data,norm='l1')

array([[-0.22641509,  0.05660377,  0.28301887,  0.43396226],
       [-0.36231884,  0.28985507,  0.14492754,  0.20289855],
       [ 0.23157895,  0.28421053, -0.21052632, -0.27368421],
       [-0.3125    ,  0.3125    ,  0.125     ,  0.25      ]])

In [17]:
preprocessing.normalize(data,norm='l2')

array([[-0.39845346,  0.09961337,  0.49806683,  0.76370247],
       [-0.68784186,  0.55027349,  0.27513674,  0.38519144],
       [ 0.45983263,  0.56434004, -0.41802966, -0.54343856],
       [-0.5976143 ,  0.5976143 ,  0.23904572,  0.47809144]])