<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Data_Analytics_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
b = np.array([[0.2,4.5],[3,6.7]])

In [8]:
b

array([[0.2, 4.5],
       [3. , 6.7]])

In [9]:
b.ndim

2

In [11]:
b.shape

(2, 2)

In [12]:
b.itemsize

8

In [13]:
b.data

In [14]:
d = np.array([1,2,3],dtype='complex')

In [15]:
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
np.arange(1,2,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [27]:
np.random.random(2)

array([0.10336867, 0.28856913])

In [29]:
a = np.arange(2,8)
print(a+2)
print(a*4)
print(a//2)
print(a-1)

[4 5 6 7 8 9]
[ 8 12 16 20 24 28]
[1 1 2 2 3 3]
[1 2 3 4 5 6]


In [33]:
a = np.random.random(2).reshape(1,2)

In [34]:
np.log(a)

array([[-1.49436795, -6.3776144 ]])

In [35]:
np.sin(a)

array([[0.22251207, 0.00169917]])

In [36]:
np.sqrt(a)

array([[0.47369862, 0.04122101]])

In [38]:
a.sum()

0.22608955843490086

In [39]:
a.min()

0.0016991716625874842

In [40]:
a.max()

0.22439038677231338

In [41]:
a.mean()

0.11304477921745043

In [42]:
a.std()

0.11134560755486295

In [43]:
np.apply_along_axis(np.mean,axis=0,arr=a)

array([0.22439039, 0.00169917])

In [44]:
np.apply_along_axis(np.mean,axis=1,arr=a)

array([0.11304478])