<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Handling_numerical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn import preprocessing

##Rescaling a feature to be between 2 values

In [4]:
feature = np.array([[-500],[-100,],[145],[345],[0]])

In [6]:
minmax = preprocessing.MinMaxScaler(feature_range=(0,1))

In [9]:
scaled_feature = minmax.fit_transform(feature)

##Standardising a feature

In [12]:
x = np.array([[120],[234],[-56],[-82],[32]])

In [13]:
scalar = preprocessing.StandardScaler()

In [15]:
standardised_values = scalar.fit_transform(x)

In [16]:
standardised_values

array([[ 0.604836  ],
       [ 1.58425792],
       [-0.90725399],
       [-1.13063092],
       [-0.151209  ]])

##Normalising features (to have values that sum to 1)

In [22]:
normalizer = preprocessing.Normalizer(norm='l2') #similarly we can use l1 norm as well.

In [23]:
x = np.array([[-200],[-111],[100],[234],[451]])

In [24]:
normalised_values = normalizer.fit_transform(x)

In [25]:
normalised_values

array([[-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.]])

##Detecting outliers

In [26]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [27]:
features, _ = make_blobs(n_samples=10,n_features=2,centers=1,random_state=1)

In [28]:
outlier_detector = EllipticEnvelope(contamination=0.1)

In [29]:
outlier_detector.fit(features)

EllipticEnvelope(assume_centered=False, contamination=0.1, random_state=None,
                 store_precision=True, support_fraction=None)

In [30]:
outlier_detector.predict(features)

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1,  1])

##Diving values using a binarizer

In [31]:
from sklearn.preprocessing import Binarizer

In [32]:
age = np.array([[11],[15],[12],[98],[73]])

In [33]:
binarizer  = Binarizer(25)

In [34]:
binarizer.fit_transform(age)

array([[0],
       [0],
       [0],
       [1],
       [1]])