<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Intro_to_backProp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
weights = np.array([0.5,0.48,-0.7])

In [3]:
alpha=0.1
street_light = np.array([[1,0,1],[0,1,1],[0,0,1],[1,1,1],[0,1,1],[1,0,1]])

In [4]:
walk_vs_stop = np.array([0,1,0,1,1,0])

In [5]:
input=street_light[0]

In [6]:
goal_prediction = walk_vs_stop[0]

In [8]:
for iteration in range(20):
  prediction = input.dot(weights)
  error = (goal_prediction-prediction)**2
  delta = prediction - goal_prediction
  weights = weights - (alpha*(input*delta))
  print("Error:",error,'Prediction:',prediction)

Error: 5.316911983140017e-06 Prediction: -0.0023058430092137705
Error: 3.4028236692096106e-06 Prediction: -0.0018446744073710164
Error: 2.177807148294282e-06 Prediction: -0.0014757395258968575
Error: 1.3937965749083403e-06 Prediction: -0.001180591620717486
Error: 8.920298079413378e-07 Prediction: -0.0009444732965739888
Error: 5.708990770825904e-07 Prediction: -0.0007555786372592799
Error: 3.653754093328579e-07 Prediction: -0.0006044629098074239
Error: 2.3384026197294315e-07 Prediction: -0.0004835703278458503
Error: 1.4965776766264926e-07 Prediction: -0.00038685626227663583
Error: 9.578097130409553e-08 Prediction: -0.00030948500982130867
Error: 6.129982163457715e-08 Prediction: -0.0002475880078569581
Error: 3.923188584614697e-08 Prediction: -0.0001980704062856109
Error: 2.5108406941548135e-08 Prediction: -0.00015845632502853313
Error: 1.6069380442568288e-08 Prediction: -0.00012676506002273769
Error: 1.0284403483261718e-08 Prediction: -0.00010141204801827897
Error: 6.5820182292947054e-09

##Building our neural network

In [9]:
import numpy as np

In [10]:
a = np.array([0,1,2,1])
b = np.array([2,2,2,3])

In [11]:
print(a+b)
print(a*b)
print(.5*a)
print(0.5+b)

[2 3 4 4]
[0 2 4 3]
[0.  0.5 1.  0.5]
[2.5 2.5 2.5 3.5]


##Learning the whole dataset

In [12]:
weights=np.array([0.5,0.48,-0.7])
alpha=0.1
streetlight = np.array([[1,0,1],[0,1,1],[0,0,1],[1,1,1],[0,1,1],[1,0,1]])
walk_vs_stop = np.array([0,1,0,1,1,0])
input = street_light[0]
goal_prediction = walk_vs_stop[0]
for iteration in range(40):
  error_for_all_lights=0
  for row_indx in range(len(walk_vs_stop)):
    input = street_light[row_indx]
    goal_prediction = walk_vs_stop[row_indx]
    prediction = input.dot(weights)
    error = (goal_prediction - prediction)**2
    error_for_all_lights+=error
    delta = prediction - goal_prediction
    weights = weights - (alpha*(input*delta))
    print("Prediction",prediction,'Error',error_for_all_lights)

Prediction -0.19999999999999996 Error 0.03999999999999998
Prediction -0.19999999999999996 Error 1.48
Prediction -0.5599999999999999 Error 1.7935999999999999
Prediction 0.6160000000000001 Error 1.9410559999999997
Prediction 0.17279999999999995 Error 2.62531584
Prediction 0.17552 Error 2.6561231104
Prediction 0.14041599999999999 Error 0.019716653055999997
Prediction 0.3066464 Error 0.50045586768896
Prediction -0.34513824 Error 0.6195762723992576
Prediction 1.006637344 Error 0.619620326734632
Prediction 0.4785034751999999 Error 0.891578952113109
Prediction 0.26700416768 Error 0.9628701776715985
Prediction 0.213603334144 Error 0.04562638435743332
Prediction 0.5347420299776 Error 0.26209136302679775
Prediction -0.26067345110016 Error 0.33004201113526527
Prediction 1.1319428845096962 Error 0.3474509359080043
Prediction 0.6274723921901568 Error 0.4862277544885286
Prediction 0.25433999330650114 Error 0.5509165866836797
Prediction 0.20347199464520088 Error 0.041400852604896655
Prediction 0.6561

##First Deep neural network

In [13]:
import numpy as np

In [14]:
np.random.seed(1)

In [15]:
def relu(x):
  return (x > 0) * x

In [16]:
alpha=0.2
hidden_size=4

In [17]:
street_light = np.array([[1,0,1],[0,1,1],[0,0,1],[1,1,1]])

In [18]:
walk_vs_stop = np.array([1,1,0,0]).T

In [19]:
weight0_1 = 2*np.random.random((3,hidden_size))-1
weight1_2 = 2*np.random.random((hidden_size,1))-1

In [23]:
layer_0 = street_light[0]
layer_1 = relu(np.dot(layer_0,weight0_1))
layer_2 = np.dot(layer_1,weight1_2)

