<a href="https://colab.research.google.com/github/Satyamaadi/python/blob/master/Numpy_index%5B0%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #importing numpy library with name np

In [3]:
row_vector = np.array([1,2,3,4,5])

In [4]:
column_vector = np.array([[1],
                          [2],
                          [3]])

In [13]:
arr = np.array([[1,2],[2,3]]) #2D array

In [14]:
matrix = np.mat([[1,2],
                 [2,3]])

In [19]:
from scipy import sparse
m = np.array([[0,2],[2,0],[3,4]])
sparse_mat = sparse.csr_matrix(m)
print(sparse_mat)

  (0, 1)	2
  (1, 0)	2
  (2, 0)	3
  (2, 1)	4


In [21]:
#selecting element
row_vector[4]

5

In [22]:
matrix[0,1]

2

In [23]:
row_vector[:]

array([1, 2, 3, 4, 5])

In [24]:
row_vector[:3]

array([1, 2, 3])

In [25]:
row_vector[3:]

array([4, 5])

In [26]:
row_vector[-1]

5

In [29]:
matrix[:2,:]

matrix([[1, 2],
        [2, 3]])

In [30]:
#Matrix Description
matrix = np.mat([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
print('Matrix shape',matrix.shape)
print('Matrix Size',matrix.size)
print('Matrix Dimension',matrix.ndim)

Matrix shape (3, 3)
Matrix Size 9
Matrix Dimension 2


In [32]:
#numpy vectorize method
matrix = np.mat([[1,2],[3,4],[5,6]])
#create a lambda function
l = lambda i : i + 100
vectorized = np.vectorize(l)
out = vectorized(matrix)
print(out)

[[101 102]
 [103 104]
 [105 106]]


In [36]:
matrix = np.mat([[1,2,3],[4,5,6],[7,8,9]])
print('Max number',np.max(matrix))
print('Min number',np.min(matrix))
#we can use np.max(matrix,axis=0 or 1 [0 for column 1 for row])

Max number 9
Min number 1


In [38]:
matrix = np.mat([[1,2,3],[4,5,6],[7,8,9]])
print('Average(or mean)',np.mean(matrix,axis=0))
print('Variance',np.var(matrix))
print('Standard Deviation',np.std(matrix))
#same as min and max we can use axis=0 or 1

Average(or mean) [[4. 5. 6.]]
Variance 6.666666666666667
Standard Deviation 2.581988897471611


In [43]:
#Reshaping matrix
matrix = np.mat([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
print('Shape Before',matrix.shape)
matrix = matrix.reshape(2,6)
print('Shape After',matrix.shape)

Shape Before (3, 4)
Shape After (2, 6)


In [45]:
matrix = np.mat([[1,2],[3,4],[5,6]])
print(matrix.T)

[[1 3 5]
 [2 4 6]]


In [47]:
matrix = np.mat([[1,2],[3,4],[5,6]])
print(matrix.flatten())#converts matrix to 1D array

[[1 2 3 4 5 6]]


In [48]:
matrix = np.mat([[1,2],[3,4],[5,6]])
print(np.linalg.matrix_rank(matrix))

2


In [50]:
matrix = np.mat([[1,2,3],[3,4,7],[5,6,6]])
print(np.linalg.det(matrix))

10.000000000000002


In [53]:
matrix = np.mat([[1,2],[3,4],[5,6]])
print(matrix.diagonal()) #it takes one addn argument as offset set to 1 returns one above diagonal and -1 returns one below main diagonal

[[1 4]]


In [54]:
matrix = np.mat([[1,2],[3,4],[5,6]])
print(matrix.trace())

[[5]]


In [57]:
A = np.mat([[1,2],[3,4],[5,6]])
B = np.mat([[1,2,3],[3,4,3]])
print(np.dot(A,B))

[[ 7 10  9]
 [15 22 21]
 [23 34 33]]


In [60]:
print(np.random.random(3))#prints 3 random value

[0.27831986 0.02291083 0.79012567]
